name: mini_hospital
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  sliding_up_panel: ^2.0.0+1
  bloc_provider: ^1.0.0
  flutter_bloc: ^8.1.1
  google_sign_in: ^5.4.2
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  image_picker:
  provider: ^6.0.4
  flutter_local_notifications: ^12.0.4
  rxdart: ^0.27.7
  lottie: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.7
  firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/animation/
    - images/google.png
    - images/login.jpg
    - images/vFilter.png



